apiVersion: v1
kind: PersistentVolume
metadata:
  name: mssql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-data-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mssql
    spec:
      securityContext:
        fsGroup: 10001
      containers:
      - name: mssql
        image: 'mcr.microsoft.com/mssql/server:2017-latest'
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql
              key: SA_PASSWORD 
        volumeMounts:
        - name: mssql-system
          mountPath: /var/opt/mssql
      volumes:
      - name: mssql-system
        persistentVolumeClaim:
          claimName: mssql-data-claim
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: mssql-service
# spec:
#   selector:
#     app: mssql
#   ports:
#     - protocol: TCP
#       port: 1433
#       targetPort: 1433
#   type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-service
spec:
  selector:
    app: mssql
  type: NodePort
  ports:
    - port: 1433
      targetPort: 1433
      nodePort: 31200