# kind: Service
# apiVersion: v1
# metadata:
#   name: todo-api-svc
# spec:
#   selector:
#     app: todo-api
#   ports:
#   - protocol: TCP
#     port: 8080
#     targetPort: 80
#   type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: todoapi-service
spec:
  selector:
    app: todo-api
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api-deploy
  labels:
    app: todo-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
      - name: todoapi
        image: sonusathyadas/todoapi:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: ConnectionStrings__SqlConnection
          value: Data Source=mssql-service;Initial Catalog=TodoDb;Persist Security Info=True;User ID=sa;Password=Password@123